// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Accelerator struct {
	ID        string
	NodeID    string
	Vendor    string
	Model     string
	VramMb    int64
	Uuid      string
	CreatedAt pgtype.Timestamptz
}

type ApiKey struct {
	KeyHash   string
	TenantID  string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Endpoint struct {
	ID        string
	TenantID  string
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

type EndpointRevision struct {
	ID             string
	EndpointID     string
	ModelVersionID string
	TrafficPercent int32
	CreatedAt      pgtype.Timestamptz
}

type HardwarePool struct {
	ID        string
	TenantID  pgtype.Text
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Model struct {
	ID        string
	TenantID  string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type ModelVersion struct {
	ID        string
	ModelID   string
	Version   string
	Source    string
	SizeBytes int64
	CreatedAt pgtype.Timestamptz
}

type Node struct {
	ID             string
	HardwarePoolID pgtype.Text
	Hostname       string
	IpAddress      string
	Status         string
	LastHeartbeat  pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Project struct {
	ID        string
	TenantID  string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Quota struct {
	ID           string
	TenantID     string
	MaxGpus      int32
	MaxEndpoints int32
	BudgetLimit  pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
}

type Replica struct {
	ID                 string
	EndpointRevisionID string
	NodeID             pgtype.Text
	Status             string
	Port               int32
	CreatedAt          pgtype.Timestamptz
}

type Tenant struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type UsageRecord struct {
	ID               string
	TenantID         string
	EndpointID       pgtype.Text
	PromptTokens     int64
	CompletionTokens int64
	DurationMs       int64
	Cost             pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID        string
	TenantID  string
	Email     string
	CreatedAt pgtype.Timestamptz
}
