// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccelerator = `-- name: CreateAccelerator :one
INSERT INTO accelerators (id, node_id, vendor, model, vram_mb, uuid)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, node_id, vendor, model, vram_mb, uuid, created_at
`

type CreateAcceleratorParams struct {
	ID     string
	NodeID string
	Vendor string
	Model  string
	VramMb int64
	Uuid   string
}

func (q *Queries) CreateAccelerator(ctx context.Context, arg CreateAcceleratorParams) (Accelerator, error) {
	row := q.db.QueryRow(ctx, createAccelerator,
		arg.ID,
		arg.NodeID,
		arg.Vendor,
		arg.Model,
		arg.VramMb,
		arg.Uuid,
	)
	var i Accelerator
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Vendor,
		&i.Model,
		&i.VramMb,
		&i.Uuid,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateTenantParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getAcceleratorsForNode = `-- name: GetAcceleratorsForNode :many
SELECT id, node_id, vendor, model, vram_mb, uuid, created_at FROM accelerators
WHERE node_id = $1
`

func (q *Queries) GetAcceleratorsForNode(ctx context.Context, nodeID string) ([]Accelerator, error) {
	rows, err := q.db.Query(ctx, getAcceleratorsForNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Accelerator
	for rows.Next() {
		var i Accelerator
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Vendor,
			&i.Model,
			&i.VramMb,
			&i.Uuid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, tenant_id, name, status, created_at FROM endpoints
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEndpoint(ctx context.Context, id string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, hardware_pool_id, hostname, ip_address, status, last_heartbeat, created_at FROM nodes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.HardwarePoolID,
		&i.Hostname,
		&i.IpAddress,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, created_at FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, tenant_id, name, status, created_at FROM endpoints
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListEndpoints(ctx context.Context, tenantID string) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeStatus = `-- name: UpdateNodeStatus :one
UPDATE nodes
SET status = $2, last_heartbeat = $3
WHERE id = $1
RETURNING id, hardware_pool_id, hostname, ip_address, status, last_heartbeat, created_at
`

type UpdateNodeStatusParams struct {
	ID            string
	Status        string
	LastHeartbeat pgtype.Timestamptz
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeStatus, arg.ID, arg.Status, arg.LastHeartbeat)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.HardwarePoolID,
		&i.Hostname,
		&i.IpAddress,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
	)
	return i, err
}

const upsertNode = `-- name: UpsertNode :one
INSERT INTO nodes (id, hardware_pool_id, hostname, ip_address, status, last_heartbeat)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    hardware_pool_id = EXCLUDED.hardware_pool_id,
    hostname = EXCLUDED.hostname,
    ip_address = EXCLUDED.ip_address,
    status = EXCLUDED.status,
    last_heartbeat = EXCLUDED.last_heartbeat
RETURNING id, hardware_pool_id, hostname, ip_address, status, last_heartbeat, created_at
`

type UpsertNodeParams struct {
	ID             string
	HardwarePoolID pgtype.Text
	Hostname       string
	IpAddress      string
	Status         string
	LastHeartbeat  pgtype.Timestamptz
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, upsertNode,
		arg.ID,
		arg.HardwarePoolID,
		arg.Hostname,
		arg.IpAddress,
		arg.Status,
		arg.LastHeartbeat,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.HardwarePoolID,
		&i.Hostname,
		&i.IpAddress,
		&i.Status,
		&i.LastHeartbeat,
		&i.CreatedAt,
	)
	return i, err
}
